print("conflict line")
print("Once Again Hello World")
print("changes in new branch2 local")
print("Welcome to the world of Python programming.")
print("This is a simple calculator program.")
print("changes in new branch1")
print("changes in new branch2 local")
print("This program can perform basic arithmetic operations.")